### ISSUE TITLE
[Filter Tasks Planner] Criar programa que filtra as tarefas do Planner que mudaram de bucket

### ISSUE THREAD

**Issue by Goestoso** [Goestoso/learning#26]
É importante criar um programa que filtra as tarefas do **Microsoft Planner** que mudaram de _bucket_ e carrega a lista dessas tarefas no arquivo `changedbuckets.json` para construir o segundo componente da automação **_Filter Tasks Planner_**.

### Critérios de Aceitação:

- Criar gatilho de execução quando o arquivo `tasksplanner.json` for criado ou modificado.
- Criar comparação de tarefas do `tasksplanner.json` com a base `Tasks Planner.xlsx` e filtrar as tarefas que mudaram de _bucket_.
- Carregar a lista dos _id_tasks_ que mudaram de _bucket_ no arquivo `changedbuckets.json`.

### Tarefas:

- [x] Criar gatilho de arquivo criado ou modificado
- [x] Criar filtro de tarefas que mudaram de _bucket_
- [x] Carregar lista de _id_tasks_ que mudaram de _bucket_

**Comment by Goestoso** [comment]
### 📝 Arquivo de configuração

O arquivo `mainsettings.yml` deve ficar em `settings/` e deve conter a seguinte estrutura:

```
# Configurações do Filter Tasks Planner
app:
    name: Filter Tasks Planner
    version: 1.0.0

observe:
    schedule: 300 # segundos
    file: C:\Caminho\Para\Arquivo\tasksplanner.json # arquivo para monitorar

others:
    tasks_excel: C:\Caminho\Para\Arquivo\Tasks Planner.xlsx
    tasks_moved: C:\Caminho\Para\Arquivo\changedbuckets.json
    tasks_new: C:\Caminho\Para\Arquivo\tasksnew.json

options:
    created: true
    modified: true

log:
    active: true
    mode: INFO # DEBUG, INFO, WARNING e ERROR
    path: C:\Caminho\Para\log\filter_tasks_planner.log
```

- **Observação**: por enquanto, o programa ainda está recebendo 100% dessas configurações.
